#!/bin/bash
file="pkgs.txt"

blacklist=("base" "linux" "linux-firmware" "linux-headers")

pacman -Qe | awk '!/nvidia/ { print $1 }' > "$file"

tmp_file=$(mktemp)
# grep -vFf <(printf "%s\n" "${blacklist[@]}") "$file" > "$tmp_file"
awk -v blacklist="${blacklist[*]}" '
  BEGIN {
    split(blacklist, words, " ");
    for (i in words) {
      blacklist_words[words[i]] = 1;
    }
  }
  {
    skip_line = 0;
    for (i in blacklist_words) {
      if ($0 == i) {
        skip_line = 1;
        break;
      }
    }
    if (!skip_line) {
      print $0;
    }
  }
' "$file" > "$tmp_file"

mv "$tmp_file" "$file"
# rm "$tmp_file"